### ISSUE TITLE
navbar cosmetic change

### ISSUE THREAD

**Issue by genxstylez** [genxstylez/potential-sansa#10]
``` css
.header a {
  font-size: 14px;
  color: #000;
  letter-spacing: 0.1em;
  line-height: 1.5;
  width: 65px;
  display: inline-block;
}
.circle-divider {
  background: #000;
  width: 4px;
  height: 4px;
  border-radius: 50%;
  display: inline-block;
  margin: 0px 8px 2px 8px;
}
```
