### ISSUE TITLE
postcontent cosmetic

### ISSUE THREAD

**Issue by genxstylez** [genxstylez/potential-sansa#12]
``` css
.article-box .article .category {
  color: #ffffff;
  height: 17px;
  font-size: 10.5px;
  border-radius: 12px;
  background-color: #c8c8c8;
  display: inline-block;
  padding: 10px;
  line-height: 0px;
  margin-bottom: 22px;
  letter-spacing: 0.075em;
}


.article-box .credit {
  margin-bottom: 5px !important;
}
```
