### ISSUE TITLE
subnavbar animation

### ISSUE THREAD

**Issue by genxstylez** [genxstylez/potential-sansa#9]
``` css
.navitems:hover .sub-nav a, .navitems:hover .sub-nav span {
    visibility: visible;
}
.navitems:hover .sub-nav {
    visibility: visible;
    height: 47px;
    visibility: all 0.2s;
}

.sub-nav {
    visibility: hidden;
    position: absolute;
    top: 224px;
    background-color: #fff;
    z-index: 3;
    width: 100%;
    left: 0px;
    height: 0px;
    line-height: 47px;
    transition: all 0.2s;

}
.sub-nav a, .sub-nav span {
    color: #646464 !important;
    visibility: hidden;
}
```
